name: Feature backend 💎
description: Add a new feature request for backend
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request form! ❤️
  - type: markdown
    attributes:
      value: |
        > Please don't forget to set assignees, effort and a priority labels
  - type: textarea
    attributes:
      label: Related issues/features 🔗
      description: If this feature is related to other please privide that information.
      value: "#"
  - type: textarea
    attributes:
      label: Feature description 📝
      description: Describe in a detailed explanation what this features is intended for.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Service base 🌐
      value: |
        Production: /path
        Sandbox: /sandbox_path
  - type: textarea
    attributes:
      label: Endpoints 🔒
      value: |
        `[METHOD]` /path_without_base
  - type: textarea
    attributes:
      label: Request 🛫
      value: |
        ```json
        EXAMPLE
        ```
  - type: markdown
    attributes:
      value: ## Response 🛬
  - type: textarea
    attributes:
      label: Success ✅
      value: |
        ```json
        EXAMPLE
        ```
  - type: textarea
    attributes:
      label: Error ❌
      value: |
        ```json
        EXAMPLE
        ```
  - type: textarea
    attributes:
      label: TODO list ✓
      value: |
        - [ ] Generate something with x on component y
        - [ ] Do cool stuff with z
  - type: textarea
    attributes:
      label: Additional files or docs 🖇
      description: You can add link, files or anything that improves the feature request information.
