name: Feature 💎
description: Add a new feature request
title: '[Feature]: '
labels: ['enhancement', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request form! ❤️
  - type: markdown
    attributes:
      value: |
        > Please don't forget to set assignees, effort and a priority labels
  - type: dropdown
    attributes:
      label: '## Feature type 📍'
      description: Please select the type of feature you are creating. Types provide a better understanding of the following information.
      multiple: false
      options:
        - 'Layout'
        - 'Layout + Backend'
        - 'Backend'
  - type: textarea
    attributes:
      label: '## Related issues/features 🔗'
      description: If this feature type requires a backend connection please provide the related issue.
      value: '#'
  - type: textarea
    attributes:
      label: '## Feature description 📝'
      description: Describe in a detailed explanation what this features is intended for.
      value: |
        ### What should this feature do
        ### TODO
        - [ ] Generate something with x on component y
        - [ ] Do cool stuff with z
    validations:
      required: true
  - type: textarea
    attributes:
      label: '## Design 🖥'
      description: Related designs for this feature.
      value: |
        - [SCREEN NAME] (VERSION OR DATE) [Check design here](http://link.com)
  - type: textarea
    attributes:
      label: '## Additional files or docs 🖇'
      description: You can add link, files or anything that improves the feature request information.
