env:
  version: ${{ github.event.release.tag_name }}
  date: ${{ github.event.release.created_at }}

name: Setup version file

# Controls when the workflow will run
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Write version file        
        uses: jsdaniell/create-json@1.1.2
        with:
          name: version.json
          dir: 'data/'
          json: '{"name": "me", "version": $version, "date": $date}'
          write-mode: overwrite
