name: "Validate PRs"

on:
  pull_request:
    types: [opened, synchronize]
    branches: ["main"]
jobs:
  validate_develop_usage:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{github.event.pull_request.head.ref}}
    steps:
      - name: "Fail if is not a valid branch"
        if: env.BRANCH != 'develop' && !startsWith(env.BRANCH, 'hotfix')
        run: echo "branch is $BRANCH" && exit 1
