name: "Validate PRs"

on:
  pull_request:
    types: [opened, synchronize]
    branches: ["main"]
jobs:
  validate_develop_usage:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{github.event.pull_request.head.ref}}
    steps:
      - name: "Validate feature is from develop"
        if: ${{ !contains(BRANCH, 'develop') || !contains(BRANCH, 'hotfix') }}
        run: echo "branch is $BRANCH" && exit 1
