name: "Validate PRs"

on:
  pull_request:
    types: [opened, synchronize]
    branches: ["main"]
jobs:
  validate_develop_usage:
    runs-on: ubuntu-latest
    steps:
      - name: "Validate feature is from develop"
        if: ${{ !contains(github.event.pull_request.head.ref, 'develop') || !contains(github.event.pull_request.head.ref, 'hotfix') }}
        run: exit 1
