name: "Validate PRs"

on:
  pull_request:
    types: [opened, synchronize]
    branches: ["main"]
jobs:
  validate_develop_usage:
    runs-on: ubuntu-latest
    env:
      BRANCH: github.event.pull_request.head.ref
    steps:
      - name: "Validate feature is from develop"
        if: ${{ !startsWith(env.BRANCH, 'develop') || !startsWith(env.BRANCH, 'hotfix') }}
        run: exit 1
