name: "Validate PRs"

on:
  pull_request:
    types: [opened, synchronize]
    branches: ["main"]
jobs:
  validate_develop_usage:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{github.event.pull_request.head.ref}}
    steps:
      - name: "Fail if is not develop"
        if: env.BRANCH != 'develop'
        run: echo "branch is $BRANCH" && exit 1
      - name: "Fail if is not hotfix"
        if: env.BRANCH != 'hotfix/*'
        run: echo "branch is $BRANCH" && exit 1
